doc(install):[TRACEFOSS] Align install file with TRG 1.02 - INSTALL.md
catenax-ng/product-traceability-foss-backend pull request #209
Opened 2023-01-26 20:03 UTC by mkanal

2023-01-31 15:49 UTC, dblankevia requested changes

2023-01-31 15:49 UTC, dblankevia commented on INSTALL.md
> +* Start the necessary infrastructure by running: ```docker-compose up``` inside [docker folder](docker)
Removing `../` breaks the links to the docker folder, which at least work if the INSTALL.md file is opened from the source code.

If we have an issue when the docs are compiled and deployed as a web page, we'll have to handle this differently.

2023-02-01 07:44 UTC, ds-jhartmann approved these changes

2023-02-01 07:53 UTC, mkanal commented on INSTALL.md
> +* Start the necessary infrastructure by running: ```docker-compose up``` inside [docker folder](docker)
```suggestion
* Start the necessary infrastructure by running: ```docker-compose up``` inside [docker folder](../docker)
```

2023-02-01 07:53 UTC, merged